name: CI
on: [push]
env:
  cache-version: v3
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        options: --health-cmd "mysqladmin ping -h localhost" --health-interval 20s --health-timeout 10s --health-retries 10
        env:
          MYSQL_ROOT_PASSWORD: P@ssw0rd!
    container:
      image: ruby:3.1.2
      env:
        BUNDLE_PATH: vendor/bundle
        KMH_DATABASE_HOST: mysql
        KMH_DATABASE_USERNAME: root
        KMH_DATABASE_PASSWORD: P@ssw0rd!
        KMH_DATABASE_SOCKET: /var/run/mysqld/mysqld.sock
        SUBDOMAIN_CONSOLE: console
        ACCESSABLE_HOSTS: .lvh.me
    steps:
    - uses: actions/checkout@v3
    - name: Restore cache vendor/bundle
      uses: actions/cache@v3
      with:
        path: vendor/bundle
        key: ${{ env.cache-version }}-bundle-${{ hashFiles('**/Gemfile.lock') }}
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.17.0
    - name: Build
      run: |
        gem install bundler
        bundle config set deployment 'true'
        bundle install --jobs 4 --retry 3
        bundle exec rails db:create db:schema:load
    - name: Run rubocop
      run: |
        bundle exec rubocop
    - name: Run test
      run: |
        bundle exec rspec --format progress
